#!/run/current-system/sw/bin/env bash

i=`echo "60 * 60 * 6" | bc`
#i=2
#i=21600
#c=1

while true; do
    waktu=`~/.xmonad/waktusolat-putrajaya-hbar`
    echo -en "$waktu\n"

    #echo -en "${c}\n"
    #c=$((c + 1))

    sleep ${i}
done
