-- XMonad configuration file by Aline Abler
import XMonad
import XMonad.Hooks.DynamicLog
import qualified Data.Map as M
import XMonad.Util.EZConfig ( additionalKeys, removeKeys )
import System.Exit

main = xmonad =<< statusBar myBar myPP toggleGapsKey myConfig

-- main configuration for xmonad
--myConfig = defaultConfig {
myConfig = def {
    terminal = "urxvt +sb -uc -bc -bg black -fg white" -- note: super+shift+enter
    , modMask = mod4Mask -- use super key as modifier
    , borderWidth = 1
    --, normalBorderColor = "#181715"
    --, focusedBorderColor = "#58C5F1"
    , focusFollowsMouse = False
    } `additionalKeys` myKeys `removeKeys` [(mod4Mask, xK_q)]

-- override some of the default keybindings and add my own
myKeys =
    [ ((mod4Mask .|. shiftMask, xK_w), spawn "feh --bg-fill --randomize ~/Wallpapers/*") -- change wallpaper
    --, ((mod4Mask .|. shiftMask, xK_q), kill) -- close window with mod-shift-Q (default is mod-shift-C)
    --, ((mod4Mask .|. shiftMask, xK_e), io (exitWith ExitSuccess)) -- close xmonad with mod-shift-E (default is mod-shift-Q)
    , ((mod4Mask .|. shiftMask, xK_r), spawn "if type xmonad; then xmonad --recompile && xmonad --restart; else xmessage xmonad not in \\$PATH: \"$PATH\"; fi") -- %! Recompile and restart xmonad
    , ((mod4Mask,               xK_x), spawn "scrot '%Y-%m-%d-%H%M%S.png' -b -u -e 'mv $f ~/Pictures/screenshots/'" )
    , ((mod4Mask .|. shiftMask, xK_x), spawn "scrot '%Y-%m-%d-%H%M%S-full.png' -b -e 'mv $f ~/Pictures/screenshots/'" )
    --, ((mod4Mask .|. shiftMask, xK_l), spawn "xlock -mode random" )
    --, ((mod4Mask .|. shiftMask, xK_l), spawn "xlock -mode forest" )
    , ((mod4Mask .|. shiftMask, xK_l), spawn "xscreensaver-command --lock" )
    ]

-- use xmobar as status bar, overriding the default config file path
myBar = "xmobar ~/.xmonad/xmobarrc.hs"

-- configuration of the status bar output generated by xmonad
myPP = xmobarPP { ppCurrent = xmobarColor "#181715" "#58C5F1" . wrap "[" "]"
                , ppTitle = xmobarColor "#14FF08" "" . shorten 120
                , ppVisible = xmobarColor "#58C5F1" "#181715" . wrap "(" ")"
                , ppUrgent = xmobarColor "#181715" "#D81816"
                , ppHidden = xmobarColor "#58C5F1" "#181715"
                , ppSep = " * "
                }

-- keybinding for toggling the gap for the statusbar (hiding the statusbar)
toggleGapsKey XConfig {XMonad.modMask = mod4Mask} = (mod4Mask, xK_b)

-- keybinding for toggling the borderline on active window (on fullscreen)
-- ...
